# Generated by Django 4.1.5 on 2023-09-09 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_articles_users_delete_testestest_articles_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='articles',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='my_blog.users'),
        ),
    ]
